version: '3'

services:
  headlamp:
    image: ghcr.io/kinvolk/headlamp:v0.12.1
    command: ["--kubeconfig","/headlamp/config/config"]
    restart: unless-stopped
    volumes:
      - ~/.kube/:/headlamp/config:ro
    ports:
      - 4466:4466
