name: Build Frontend

on:
  pull_request:
    paths:
    - 'frontend/**'
    - 'Makefile'
    - '.github/**'
    - 'app/**'
    - 'plugins/**'
  push:
    branches:
      - main
    paths:
    - 'frontend/**'
    - Makefile
    - '.github/**'
    - 'app/**'
    - 'plugins/**'

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        make frontend-install-ci

    - name: Run linter
      run: |
        make frontend-lint

    - name: Run tests
      run: |
        make frontend-test

    - name: Build Frontend
      run: |
        make frontend-build

    - name: Test plugins
      run: |
        make plugins-test

    - name: Build docs
      run: |
        make docs

    - name: Build storybook
      run: |
        make frontend-build-storybook
